'''
MYSQL_HOST ='bvgp2j3zwl97w1rbitly-mysql.services.clever-cloud.com'
MYSQL_USER ='ulnnjeupsxhgbqy7'
MYSQL_PASSWORD ='U7dBZmVwYdOVg6ohYOqa'
MYSQL_DB ='bvgp2j3zwl97w1rbitly'
HEX_SEC_KEY='d5fb8c4fa8bd46638dadc4e751e0d68d'
'''

'''
DB_HOST='bvgp2j3zwl97w1rbitly-mysql.services.clever-cloud.com'
DB_USERNAME='ulnnjeupsxhgbqy7'
DB_PASSWORD='U7dBZmVwYdOVg6ohYOqa'
DATABASE='bvgp2j3zwl97w1rbitly'
KEY_FOR_APP='my secret key'
'''